# Generated by Django 3.0.4 on 2020-03-21 10:33

from django.db import migrations
import django_fsm
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_test_relation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientattributetransaction',
            name='status',
            field=django_fsm.FSMField(choices=[('Pending', 'PENDING'), ('Rejected', 'REJECTED'), ('Approved', 'APPROVED')], default=users.models.AttributeStatus['PENDING'], max_length=50, protected=True),
        ),
    ]
