# Generated by Django 3.0.4 on 2020-03-18 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assistant', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('assistant', 'client', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='ClientAttributeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_name', models.CharField(max_length=250)),
                ('attribute_old_value', models.CharField(max_length=250)),
                ('attribute_new_value', models.CharField(max_length=250)),
                ('status', django_fsm.FSMField(choices=[('Pending', 'PENDING'), ('Rejected', 'REJECTED'), ('Approved', 'APPROVED')], default=users.models.AttributeStatus['PENDING'], max_length=50)),
                ('assistant_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_client', to='users.AssistantClient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Managerassistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assistant', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('manager', 'assistant', 'is_active')},
            },
        ),
    ]
