# Generated by Django 3.0.4 on 2020-03-21 06:41

from django.db import migrations
from django.db import transaction

from django.contrib.auth.hashers import make_password

def create_default_groups(apps, schema_editor):
    """[summary]

    Arguments:
        apps {[type]} -- [description]
        schema_editor {[type]} -- [description]
    """
    Group = apps.get_model('auth', 'Group')
    groups =["Manager", "Associate", "Client"]
    with transaction.atomic():
        for group in groups:
            _group = Group.objects.create(
                name = group
            )


def reverse_groups(apps, schema_editor):
    groups =["Manager", "Associate", "Client"]
    Group = apps.get_model('auth', 'Group')
    for _group in groups:
        Group.objects.filter(name=_group).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, reverse_groups)
    ]
